/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yi2jLGH
 */
import Image from 'next/image';

const FeaturedStories = () => {
  return (
    <div className='grid grid-cols-1 lg:grid-cols-3 gap-6'>
      <div className='lg:col-span-2'>
        <div className='rounded-lg overflow-hidden'>
          <Image
            alt='Featured story'
            className='w-full h-64 object-cover lg:h-96'
            height='450'
            src='https://images.unsplash.com/photo-1612367980327-7454a7276aa7?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
            style={{
              aspectRatio: '800/450',
              objectFit: 'cover',
            }}
            width='800'
          />
        </div>
        <h2 className='mt-4 text-2xl font-bold leading-tight'>
          The Future of Work in a Post-Pandemic World
        </h2>
        <p className='mt-2 text-gray-500'>
          As the world grapples with the ongoing ramifications of the COVID-19
          pandemic, businesses are also trying to figure out what the future of
          work will look like...
        </p>
      </div>
      <div className='space-y-6 lg:space-y-0 lg:grid lg:grid-cols-1 lg:gap-6'>
        <div>
          <div className='rounded-lg overflow-hidden'>
            <Image
              alt='Top story'
              className='w-full h-32 object-cover lg:h-48'
              height='225'
              src='https://images.unsplash.com/photo-1612367980327-7454a7276aa7?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
              style={{
                aspectRatio: '400/225',
                objectFit: 'cover',
              }}
              width='400'
            />
          </div>
          <h2 className='mt-4 text-xl font-bold leading-tight'>
            The Rise of Remote Work
          </h2>
          <p className='mt-2 text-gray-500'>
            The pandemic has accelerated the shift towards a more flexible
            workforce, with many companies adopting remote work policies...
          </p>
        </div>
        <div>
          <div className='rounded-lg overflow-hidden'>
            <Image
              alt='Top story'
              className='w-full h-32 object-cover lg:h-48'
              height='225'
              src='https://images.unsplash.com/photo-1612367980327-7454a7276aa7?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
              style={{
                aspectRatio: '400/225',
                objectFit: 'cover',
              }}
              width='400'
            />
          </div>
          <h2 className='mt-4 text-xl font-bold leading-tight'>
            The Impact of COVID-19 on Small Businesses
          </h2>
          <p className='mt-2 text-gray-500'>
            Small businesses have been disproportionately affected by the
            economic fallout from the COVID-19 pandemic...
          </p>
        </div>
      </div>
    </div>
  );
};

export default FeaturedStories;
